version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db.user
      POSTGRES_PASSWORD: s3cureP4ss!2023
      POSTGRES_DB: rentalstore_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: rentalstore_db
      DB_USER: db.user
      DB_PASSWORD: s3cureP4ss!2023
      DB_PORT: 5432

volumes:
  db_data:
